---
- name: Install and configure httpd
  hosts: all
  become: yes
  tasks:
    - name: Install httpd
      package:
        name: httpd
        state: present

    - name: Update httpd port to 81
      lineinfile:
        path: /etc/httpd/conf/httpd.conf
        regexp: '^Listen 80$'
        line: 'Listen 81'
        notify: restart httpd

  handlers:
    - name: restart httpd
      service:
        name: httpd
        state: restarted
