---
- name: Add the 'student' user to the wheel group
  hosts: all
  become: yes
  become_method: su
  become_user: root
  tasks:
    - name: Add 'student' to the wheel group
      user:
        name: student
        groups: wheel
        append: yes
